"""Hygiene validation for work records (Slice 4).

Reports problems; never repairs, deletes, or rewrites human records.
Read-only (one exception: the generated-marker check reads docs/INDEX.md).
"""

from __future__ import annotations

import datetime
import re

from linkbus.validate import URI_RE

TASK_STATUS = frozenset(["QUEUED", "ACTIVE", "BLOCKED", "VERIFY", "DONE", "CANCELLED"])
ESC_CLASS = frozenset(
    [
        "HUMAN_DECISION",
        "LIVE_AUTH_REQUIRED",
        "EVIDENCE_STALE",
        "PROVIDER_MISSING",
        "CONTRACT_DRIFT",
        "TEST_FAILURE",
        "AMBIGUOUS_RESULT",
        "SECURITY_BOUNDARY",
    ]
)
ESC_STATUS = frozenset(["OPEN", "RESOLVED", "CANCELLED"])
DECISION_STATUS = frozenset(["PROPOSED", "ACCEPTED", "SUPERSEDED", "REJECTED"])
ARCH_STATUS = frozenset(["DRAFT", "CURRENT", "SUPERSEDED"])

ID_PATTERNS = {
    "task": re.compile(r"^TASK-[0-9]{4,}$"),
    "escalation": re.compile(r"^ESC-[0-9]{4,}$"),
    "decision": re.compile(r"^ADR-[0-9]{4,}$"),
    "architecture": re.compile(r"^[A-Z0-9][A-Z0-9_-]*$"),
}
ANY_RECORD_ID = re.compile(r"^(TASK|ESC|ADR)-[0-9]{4,}$")
DATE_RE = re.compile(r"^([0-9]{4})-([0-9]{2})-([0-9]{2})$")

INDEX_MARKER = "<!-- GENERATED BY integration/work/build_index.py — DO NOT EDIT BY HAND -->"

COMMON_REQUIRED = ("schema", "id", "kind", "title", "status", "owner", "created", "updated")


def error(code: str, message: str, source: str = "") -> dict:
    record = {"code": code, "message": message}
    if source:
        record["source"] = source
    return record


def _norm(text: str) -> str:
    return text.upper().replace("_", "-")


def check_binding(doc: dict) -> list[dict]:
    source = doc.get("_source", "")
    stem = source.rsplit("/", 1)[-1].removesuffix(".md")
    rid = str(doc.get("id", ""))
    if _norm(stem) != _norm(rid) and not _norm(stem).startswith(_norm(rid) + "-"):
        return [error("FILENAME_ID_MISMATCH", f"id {rid} not bound to filename {stem}", source)]
    return []


def check_dates(doc: dict) -> list[dict]:
    source = doc.get("_source", "")
    dates = {}
    for field in ("created", "updated"):
        value = doc.get(field)
        match = DATE_RE.match(str(value or ""))
        if not match:
            return [error("INVALID_DATE", f"bad {field}: {value!r}", source)]
        try:
            dates[field] = datetime.date(*map(int, match.groups()))
        except ValueError:
            return [error("INVALID_DATE", f"bad {field}: {value!r}", source)]
    if dates["updated"] < dates["created"]:
        return [error("INVALID_DATE", "updated before created", source)]
    return []


def check_refs(values: object, doc: dict, known_ids: set, registered: set) -> list[dict]:
    errors: list[dict] = []
    source = doc.get("_source", "")
    if not isinstance(values, list):
        return [error("INVALID_REFS", "reference list malformed", source)]
    seen: set[str] = set()
    for value in values:
        if not isinstance(value, str) or not value:
            errors.append(error("INVALID_REFS", "empty reference entry", source))
            continue
        if value in seen:
            errors.append(error("DUPLICATE_RELATED", f"duplicate reference: {value}", source))
        seen.add(value)
        if value.startswith("kolmaf://"):
            if not URI_RE.match(value):
                errors.append(error("INVALID_URI", f"malformed uri: {value}", source))
            elif value not in registered:
                errors.append(error("UNKNOWN_URI", f"unregistered uri: {value}", source))
        elif ANY_RECORD_ID.match(value) and value not in known_ids:
            errors.append(error("BROKEN_REFERENCE", f"unknown record: {value}", source))
    return errors


def validate_record(doc: dict, known_ids: set, registered: set) -> list[dict]:
    errors: list[dict] = []
    source = doc.get("_source", "")
    if doc.get("schema") != "kolmaf-work-record/v1":
        errors.append(error("INVALID_SCHEMA", "schema must be kolmaf-work-record/v1", source))
    kind = doc.get("kind")
    if kind != doc.get("_dir_kind"):
        errors.append(
            error("KIND_MISMATCH", f"kind {kind!r} not in {doc.get('_dir_kind')} dir", source)
        )
        return errors
    pattern = ID_PATTERNS.get(str(kind))
    if pattern is None or not pattern.match(str(doc.get("id", ""))):
        errors.append(error("INVALID_ID", f"bad {kind} id", source))
    errors.extend(check_binding(doc))
    for field in COMMON_REQUIRED:
        if doc.get(field) in (None, ""):
            errors.append(error("MISSING_FIELD", f"missing {field}", source))
    if not isinstance(doc.get("owner"), str) or not doc["owner"].strip():
        errors.append(error("MISSING_OWNER", "owner required", source))
    errors.extend(check_dates(doc))
    status = doc.get("status")
    if kind == "task":
        if status not in TASK_STATUS:
            errors.append(error("UNKNOWN_TASK_STATUS", f"bad status {status!r}", source))
        if status == "BLOCKED" and not doc.get("blocked_by"):
            errors.append(error("BLOCKED_WITHOUT_BLOCKER", "BLOCKED needs blocked_by", source))
    elif kind == "escalation":
        if doc.get("class") not in ESC_CLASS:
            errors.append(error("UNKNOWN_ESCALATION_CLASS", "bad class", source))
        if status not in ESC_STATUS:
            errors.append(error("UNKNOWN_ESCALATION_STATUS", f"bad status {status!r}", source))
        if not doc.get("reason"):
            errors.append(error("MISSING_FIELD", "missing reason", source))
        if status == "RESOLVED" and not doc.get("resolution"):
            errors.append(error("MISSING_FIELD", "RESOLVED needs resolution", source))
        task = doc.get("task")
        if task is not None:
            if not ANY_RECORD_ID.match(str(task)) or not str(task).startswith("TASK-"):
                errors.append(error("BROKEN_REFERENCE", f"bad escalation task: {task}", source))
            elif str(task) not in known_ids:
                errors.append(error("BROKEN_REFERENCE", f"unknown task: {task}", source))
    elif kind == "decision":
        if status not in DECISION_STATUS:
            errors.append(error("UNKNOWN_DECISION_STATUS", f"bad status {status!r}", source))
        if status == "SUPERSEDED":
            errors.extend(check_supersession(doc, known_ids))
    elif kind == "architecture":
        if status not in ARCH_STATUS:
            errors.append(error("UNKNOWN_ARCH_STATUS", f"bad status {status!r}", source))
        if status == "SUPERSEDED":
            errors.extend(check_supersession(doc, known_ids))
    errors.extend(check_refs(doc.get("related", []), doc, known_ids, registered))
    for field in ("blocked_by", "depends_on"):
        if doc.get(field) is not None:
            errors.extend(check_refs(doc[field], doc, known_ids, registered))
    if not isinstance(doc.get("_body"), str) or not doc["_body"].strip():
        errors.append(error("MISSING_FIELD", "empty body", source))
    return errors


def check_supersession(doc: dict, known_ids: set) -> list[dict]:
    source = doc.get("_source", "")
    target = doc.get("superseded_by")
    if not target:
        return [error("SUPERSEDED_WITHOUT_REPLACEMENT", "SUPERSEDED needs superseded_by", source)]
    if str(target) not in known_ids:
        return [error("BAD_SUPERSESSION", f"unknown replacement: {target}", source)]
    return []


def validate_all(records: list[dict], registered: set, project_root=None) -> list[dict]:
    errors: list[dict] = []
    seen: set[str] = set()
    for doc in records:
        rid = str(doc.get("id", ""))
        if rid in seen:
            errors.append(
                error("DUPLICATE_ID", f"duplicate record id: {rid}", doc.get("_source", ""))
            )
        seen.add(rid)
    known_ids = {str(d.get("id", "")) for d in records}
    for doc in records:
        errors.extend(validate_record(doc, known_ids, registered))
    if project_root is not None:
        index = project_root / "docs" / "INDEX.md"
        if index.is_file():
            first = index.read_text(encoding="utf-8").splitlines()
            if not first or first[0].strip() != INDEX_MARKER:
                errors.append(error("GENERATED_EDITED", "docs/INDEX.md marker damaged", "INDEX.md"))
    return errors
